# Generated by Django 5.0.2 on 2024-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0002_invoice_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('p_number', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('pass1', models.CharField(blank=True, max_length=15, null=True)),
                ('pass2', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
    ]
